import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import ClientLayout from "./ClientLayout";
import { Toaster } from 'sonner';
import { ReduxProvider } from './providers';
import { AuthProvider } from "./context/AuthContext";
import NavigationGuard from "./components/NavigationGuard";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Respyr Dashboard",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
       <ReduxProvider>
          <ClientLayout>
            <AuthProvider>
          <NavigationGuard />
            {children}
             </AuthProvider>
            <Toaster />
          </ClientLayout>
        </ReduxProvider>
      </body>
    </html>
  );
}